from __future__ import annotations
from typing import Any, Dict, Protocol, Tuple, Union
from .schema import Task, DecisionContext, AgentDecision

class Environment(Protocol):
    def reset(self) -> Dict[str, Any]: ...
    def observe(self) -> Dict[str, Any]: ...
    def expected_state(self) -> Dict[str, Any]: ...
    def step(self, action: str) -> Tuple[Dict[str, Any], bool, Dict[str, Any]]: ...
    def verify(self) -> Dict[str, float]: ...
    def rollback_local(self) -> None: ...

class Agent(Protocol):
    model_id: str
    version: str
    def act(self, context: DecisionContext) -> Union[str, AgentDecision]: ...
